2025-09-25 16:22:55,852 - INFO - HTTP Request: GET https://uzsziqehmunidzzhoeij.supabase.co/rest/v1/scraping_progress?select=%2A&limit=1 "HTTP/2 200 OK"
2025-09-25 16:22:55,859 - INFO - Scraping progress table already exists.
2025-09-25 16:22:56,186 - INFO - HTTP Request: GET https://uzsziqehmunidzzhoeij.supabase.co/rest/v1/scraping_progress?select=last_processed_id&id=eq.5 "HTTP/2 200 OK"
2025-09-25 16:22:56,192 - INFO - Resuming from region ID: 47
2025-09-25 16:22:56,682 - INFO - Found 8 regions
2025-09-25 16:22:56,682 - INFO - Processing region: Wellington City
2025-09-25 16:23:27,118 - ERROR - Error fetching suburbs from https://www.propertyvalue.co.nz/wellington/wellington/wellington-city/47: HTTPSConnectionPool(host='www.propertyvalue.co.nz', port=443): Read timed out.
2025-09-25 16:23:27,223 - ERROR - Error details: Traceback (most recent call last):
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\urllib3\response.py", line 754, in _error_catcher
    yield
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\urllib3\response.py", line 1219, in read_chunked
    self._update_chunk_length()
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\urllib3\response.py", line 1138, in _update_chunk_length
    line = self._fp.fp.readline()  # type: ignore[union-attr]
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\urllib3\response.py", line 1063, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\urllib3\response.py", line 1202, in read_chunked
    with self._error_catcher():
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\urllib3\response.py", line 759, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.propertyvalue.co.nz', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Next.js\realEstate\nzlouis-property-ai-engine\property_wellington.py", line 207, in fetch_suburbs
    response = requests.get(region_url, headers=headers, timeout=30)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\requests\sessions.py", line 747, in send
    r.content
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.propertyvalue.co.nz', port=443): Read timed out.

2025-09-25 16:23:27,227 - INFO - Found 0 suburbs in region: Wellington City
2025-09-25 16:23:27,438 - INFO - HTTP Request: PATCH https://uzsziqehmunidzzhoeij.supabase.co/rest/v1/scraping_progress?id=eq.5 "HTTP/2 200 OK"
2025-09-25 16:23:27,444 - INFO - Updated last processed region ID to: 47
